import '../styles/globals.css';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import { CartProvider } from './context/CartContext';

export const metadata = {
  title: 'Telur Cerdas',
  description: 'Smart, fresh, and quality eggs for everyone.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

// import clsx from 'clsx';
// import type { Metadata } from 'next';
// import { Poppins } from 'next/font/google';
// import './globals.css';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700', '800'],
//   style: ['normal', 'italic'],
//   variable: '--font-poppins',
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang='en'>
//       <body className={clsx(poppins.variable, 'antialiased')}>{children}</body>
//     </html>
//   );
// }
